apiVersion: v1
kind: pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
  spec:
    template:
      metadata:
        name: myapp
        labels:
          type: backend
      containers:
        - name: nginx-container
          image: nginx 
    replicaSet: 2
    selectors:
      matchLabels:
        type: backend
