apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    app: front
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: node01    # node name to be specifies if cluster does not contain schedulers